spring:
  application:
    name: backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  auth-enabled: ${APP_AUTH_ENABLED:false}

server:
  port: 8080

powens:
  domain: ${POWENS_DOMAIN}
  client-id: ${POWENS_CLIENT_ID}
  client-secret: ${POWENS_CLIENT_SECRET}
  manage-token: ${POWENS_MANAGE_TOKEN}
  redirect-url: ${POWENS_REDIRECT_URL}
